version: "2"

run:
    timeout: 5m

formatters:
    enable:
        - gofumpt

linters:
    enable:
        - asasalint
        - asciicheck
        - bidichk
        - bodyclose        # HTTP body close
        - canonicalheader
        - containedctx
        - contextcheck
        - copyloopvar
        - decorder
        - dogsled
        - dupword
        - durationcheck
        - embeddedstructfieldcheck
        - errcheck         # Unchecked errors
        - errchkjson
        - errname
        - errorlint
        - exhaustive
        - exptostd
        - fatcontext
        - forcetypeassert
        - gocheckcompilerdirectives
        - gocritic         # Advanced checks
        - godot
        - godox
        - goprintffuncname
        - gosec            # Security issues
        - govet            # Built-in vet
        - grouper
        - iface
        - inamedparam
        - ineffassign
        - interfacebloat
        - intrange
        - iotamixing
        - loggercheck
        - makezero
        - mirror
        - misspell         # Typos in comments/strings
        - musttag
        - nakedret
        - nilerr
        - nilnesserr
        - nilnil
        - nlreturn
        - noctx
        - nolintlint       # Enforce nolint comments
        - nonamedreturns
        - perfsprint
        - predeclared
        - protogetter
        - reassign
        - recvcheck
        - rowserrcheck
        - sloglint
        - sqlclosecheck
        - staticcheck      # Go vet++
        - testableexamples
        - thelper
        - unconvert        # Unnecessary conversions
        - unparam
        - unused
        - usestdlibvars
        - usetesting
        - wastedassign
        - whitespace
#        - wsl_v5
#        - tagliatelle
#        - modernize
#        - ireturn
#        - varnamelen
#        - prealloc

    settings:
        gofumpt:
            extra-rules: true
        gocritic:
            disabled-checks:
                - ifElseChain
                - elseif
                - appendAssign
                - assignOp
                - unlambda
        gosec:
            excludes:
                - G104
                - G204
                - G301
                - G302
                - G304
                - G306

issues:
    exclude-rules:
        -   path: _test\.go
            linters:
                - gosec
                - errcheck
        -   path: testutils/*.go
            linters:
                - gosec
                - errcheck

output:
    path-mode: "abs"
    sort-results: true
    formats:
        text:
            colors: true
            path: stdout
            print-issued-lines: true
            print-linter-name: true
    sort-order:
        - linter
        - file
        - severity
